name: leech

on:
  push:
    paths:
    - '.github/workflows/leech.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        url:
        - https://srv55.mexa.sh:183/d/efsdokt2xoy775ghkd3qqdchbtxjcllizghosrdpsqncch6luizheu3du2g3fixvvhxeuqba/G-RJ01277982-v24.12.04.part4.rar
        - https://srv653.mexa.sh:183/d/d5sea22xxoy775ghid3amci7boforip4lc2p6fdezj6wikzsbzhwyddzz232c7e5pp2tnvw7/G-RJ01356701-v25.03.30.zip
        - https://srv11.mexa.sh:183/d/lnsnekl2xoy775ghkd3rwfc5kenwzvsonl6mrz6pg45xdi2wx77dv4vauotkb23usmtaec3h/G-RJ01277982-v24.12.04.part1.rar
        - https://srv928.mexa.sh:183/d/3zsnwkl2xoy775ghkd3ryskdkixr52bshozsmfoofqrd7sv2cowbgdfxq7avxn6i57s2pawq/G-RJ01277982-v24.12.04.part2.rar
        - https://srv11.mexa.sh:183/d/lnsm6kl2xoy775ghkd3v2e25ddswqusvcmipdhop4yjmfranjcnknxgg7ewmdmtj7foeijes/G-RJ01277982-v24.12.04.part3.rar
    runs-on: ubuntu-latest
    steps:
    - uses: actions/cache@v4
      id: cache
      with:
        path: megatools-1.11.5.20250706-linux-x86_64
        key: megatools-1.11.5.20250706-linux-x86_64
    - name: Mega
      if: steps.cache.outputs.cache-hit != 'true'
      run: |
        curl -OL https://xff.cz/megatools/builds/builds/megatools-1.11.5.20250706-linux-x86_64.tar.gz
        tar xvf *.gz
    - name: Leech
      run: |
        mkdir leech && cd leech
        if [[ ${{ matrix.url }} == *"mega.nz"* ]]
        then
          ../megatools*/megatools dl --path ./ ${{ matrix.url }}
        elif [[ ${{ matrix.url }} == *"drive.google"* ]]
        then
          pip install gdown && gdown ${{ matrix.url }}
        else
          curl -OL --insecure ${{ matrix.url }}
        fi
        find . -size +2000M -exec split -b 1G --numeric-suffixes=1 {} {}.0 \;
        find . -size +2000M -exec rm {} \;
    - name: Upload
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: leech/*
        tag: cache
        overwrite: true
        file_glob: true
